### PR TITLE
Feat/iteration0/ds

### PR DESCRIPTION
**Pull request by dsstevens**
Changes made on this first branch are basic layout setup on the HTML and CSS. We also added event listeners to the javascript file and added a data.js file for the future saved palette arrays to live.

### CODE REVIEW

**Comment by nicolerue** [comment]
Great! Things to do still:
- look at / fix the html/css to make the lock codes stay within the main boxes. 
- Play around with the separator line if it helps with centering the page. 
- Play around with the body's flex properties in css so that it's center, but also making sure that the locks stay in place. 
- make sure we organize/separate our query selectors, functions, and event listeners.

**Review by MaryBruff — APPROVED** [review]
Great start to the comp. Let's figure out that lock button and start pseudocoding JS for iteration 1.

**Comment by EGavinG** [comment]
Stellar work! I'll take on the bullet for "play around with the body's flex properties in css so that it's center, but also making sure that the locks stay in place." Let's continue to work on getting this app moved forward and we can come back to discuss changes.

**Review by EGavinG — COMMENTED** [review]
Stellar work! I'll take on the bullet for "play around with the body's flex properties in css so that it's center, but also making sure that the locks stay in place." Let's continue to work on getting this app moved forward and we can come back to discuss changes.

**Pull request merged**
